### PR TITLE
Add PatchOptions.Path field.

### PR DESCRIPTION
**Pull request by shurcooL**
Gerrit API docs: https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#get-patch.

### CODE REVIEW

**Comment by andygrunwald** [comment]
LGTM

**Comment by shurcooL** [comment]
Thanks for the quick review.

I have a handful more of local patches I'll be trying to upstream next. I'll start with the easiest and least disruptive ones first, and leave hardest ones for the end.

@andygrunwald How do you feel about using using the squash merge strategy for merging simple PRs that make one logical change?

image

That way, there's only one entry in the [history](https://github.com/andygrunwald/go-gerrit/commits/104d92ee699ed5ddc12363bc6201370756b92302) instead of two, making it more readable and nicer.

**Comment by andygrunwald** [comment]
> I have a handful more of local patches I'll be trying to upstream next. I'll start with the easiest and least disruptive ones first, and leave hardest ones for the end.

This sounds good and I am looking forward to this!

> @andygrunwald How do you feel about using using the squash merge strategy for merging simple PRs that make one logical change?

Personally, I don't have a strict opinion about this.
I understand the request in terms of having a clean history. For simple PRs this make sense. I would agree with everyone who has a favor for this. But i (personally) don't mind have a Merge commit in.
But there i am free what the team (you, @opalmer and i) vote for.

For complex PRs with a couple of commits where every commit has a real use case and an explainable commit message (e.g. https://chris.beams.io/posts/git-commit/), i would disagree to do this, because then the information gets lost.

If you want to go for it, feel free :)
I will not block anyone. If you want to get more opinions about this, i suggest to open a new ticket here and mention @opalmer also. There we can discuss this in detail and maybe some other OSS maintainers hook on (i guess it is harder to find this discussion in this PR instead of a separate one)

**Comment by shurcooL** [comment]
> For complex PRs with a couple of commits where every commit has a real use case and an explainable commit message (e.g. https://chris.beams.io/posts/git-commit/), i would disagree to do this, because then the information gets lost.

Oh, I completely agree, I think each logical commit with a clean commit message (rather than just a fixup commit to address review feedback) should be preserved in `master`. But I would still prefer "rebase and merge" strategy for that over the "merge commit" one.

But what I care more about is just avoiding the merge commit for small, single-logical-commit PRs (such as this one).

**Comment by andygrunwald** [comment]
Okay, let's try this :)

**Pull request merged**
