### PR TITLE
Query url parameters should not escape + or :

### PR DESCRIPTION
**Pull request by opalmer**
See #18 for details.

### CODE REVIEW

**Comment by opalmer** [comment]
@andygrunwald, @perolausson PTAL. So far as I can tell, this change should fix the issue discovered in #18.

I'm not sure this is the best approach but neither `net/url` or `github.com/google/go-querystring/query` appear to have a way of excluding some symbols from parsing and writing our own from scratch didn't seem ideal either.

**Comment by andygrunwald** [comment]
I am on a trip until 21st October. I try to have a look at it in between,
but I am not sure if I can afford this. The trip is quite busy and tough.

If you are sure that this will fix it and (even better) provide a unit /
regression test with it: Go for it.

@opalmer you know I trust you in this project :) so we are equal :)

Am Donnerstag, 13. Oktober 2016 schrieb opalmer :

**Comment by opalmer** [comment]
> If you are sure that this will fix it and (even better) provide a unit / regression test with it: Go for it.

Already added a test in d703d1455ccddafcdec125c64fbf0f89128f7af7 for exactly this :).  Prior to the fix this new unittest would have failed.

**Comment by opalmer** [comment]
@perolausson, have you had a chance to test this?

**Comment by perolausson** [comment]
No I'm sorry. Snowed under.

**Comment by opalmer** [comment]
@perolausson, any chance you could take a look at this sometime this week?

**Comment by opalmer** [comment]
I'm going to go ahead and merge this within the next couple of days if there are not any objections.  The testing I've done seems to indicate this will fix the original problem without causing any new ones.  If that turns out to not be the case it's pretty easy to either roll this back or apply a patch.

**Comment by andygrunwald** [comment]
Go ahead @opalmer.
Thx for your effort

**Pull request merged**
