### PR TITLE
add support for Change API's "Set Commit Message" endpoint

### PR DESCRIPTION
**Pull request by srabraham**
Thanks for your excellent Gerrit API client! I wish Google offered something like this.

### CODE REVIEW

**Comment by srabraham** [comment]
I fixed the lint issue

**Comment by andygrunwald** [comment]
Thanks Sean, for taking the time and the PR!
Would you mind to add a basic unit test here as well?
Then we are ready to go and merge.

**Comment by srabraham** [comment]
Alright, added a couple of tests

**Comment by andygrunwald** [comment]
Thanks @srabraham!

**Pull request merged**
